#!/bin/bash -l

#SBATCH -A g2019003
#SBATCH -p core
#SBATCH -n 4
#SBATCH -t 01:00:00
#SBATCH -J Maker_hmm_Marten_Klaesson
#SBATCH --mail-type=ALL
#SBATCH --mail-user mklaesson91@gmail.com

# Load modules
module load bioinfo-tools
module load maker


# Commands
hmm-assembler.pl /home/martene/Genome_Analysis/Analysis/Pilon_run/Pilon_output.fasta . > /home/martene/Genome_Analysis/Analysis/maker/hmmoutput/my_genome_hmm.hmm
