#!/bin/bash -l
#SBATCH -A g2019003
#SBATCH -p core
#SBATCH -n 4
#SBATCH -t 0:20:00
#SBATCH -J scaffold-10-sort
#SBATCH --mail-type=ALL
#SBATCH --mklaesson91@gmail.com
# Load modules
module load bioinfo-tools
module load samtools
for file in /home/martene/Genome_Analysis/Analysis/Bowtie2_Tophat/outputfiles/*
do
	output=$(basename $file)
	samtools sort $file/accepted_hits.bam -o /home/martene/Genome_Analysis/Analysis/Bowtie2_Tophat/output_sorted/accepted_hits_sorted_2019-05-24_$output.bam
done
